# Generated by Django 3.0.7 on 2020-06-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_auto_20200622_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(default='e57373', help_text='Color code', max_length=200, verbose_name='Color code'),
        ),
    ]
