# Generated by Django 3.0.7 on 2020-06-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0006_auto_20200622_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Category name', max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='step',
            name='description',
            field=models.TextField(help_text='Step description', max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='step',
            name='title',
            field=models.CharField(help_text='Step name', max_length=200, verbose_name='Title'),
        ),
    ]
