# Generated by Django 3.0.7 on 2020-06-24 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0007_auto_20200623_1150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ['number'], 'verbose_name': 'Step', 'verbose_name_plural': 'Steps'},
        ),
    ]
