# Generated by Django 3.0.7 on 2020-06-29 07:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0008_auto_20200624_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='lookup_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
