# Generated by Django 3.0.7 on 2020-06-30 09:41

from django.db import migrations, models
import todoapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0009_step_lookup_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='number',
            field=models.IntegerField(default=todoapp.models.Step.order, verbose_name='Step number'),
        ),
    ]
